import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowUpRight, CheckCircle2, Compass } from 'lucide-react'
import styled from 'styled-components'
import { Badge } from './ui/badge'
import { Sheet, SheetContent, SheetTitle } from './ui/sheet'
import type { RoadmapNode } from '../data/broker-roadmap'
const homeUrl = import.meta.env.BASE_URL

type CareerRoadmapProps = { careerName: string; intro: string; nodes: RoadmapNode[]; links: string[][]; canvasHeight?: number; verticalScale?: number }

export function CareerRoadmap({ careerName, intro, nodes, links, canvasHeight = 1540, verticalScale = 1 }: CareerRoadmapProps) {
  const [selected, setSelected] = useState<RoadmapNode | null>(null)
  const displayNodes = useMemo(() => nodes.map((node) => ({ ...node, y: node.y * verticalScale })), [nodes, verticalScale])
  const lineSegments = useMemo(() => {
    const nodesById = Object.fromEntries(displayNodes.map((node) => [node.id, node]))
    return links.map(([fromId, toId]) => [nodesById[fromId], nodesById[toId]])
  }, [displayNodes, links])
  return <Page>
    <Header><a className="back" href={homeUrl}><ArrowLeft size={16} /> All careers</a><a className="brand" href={homeUrl}><span>MP</span>Mortgage Paths</a><div className="route-label">Career pathway</div></Header>
    <main><RoadmapSection><RoadmapHeader><div><Eyebrow><span /> {careerName}</Eyebrow><h1>Your pathway into<br /><em>{careerName.toLowerCase()}.</em></h1></div><p>{intro}</p></RoadmapHeader><Legend><span><i className="core-dot" /> Core pathway</span><span><i className="optional-dot" /> Optional specialism</span><span>Click any stop to open its guide <ArrowUpRight size={13} /></span></Legend><RoadmapCanvas $height={canvasHeight}><svg className="connectors" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{lineSegments.map(([from, to]) => <line key={`${from.id}-${to.id}`} x1={from.x} y1={from.y + 5} x2={to.x} y2={to.y} />)}</svg>{displayNodes.map((node) => <RoadmapStop key={node.id} node={node} onClick={() => setSelected(node)} />)}</RoadmapCanvas><RoadmapFoot><Compass size={20} /><span>This is a guide, not a race. You can take a detour, revisit a step, or start building experience before you’ve ticked every box.</span></RoadmapFoot></RoadmapSection></main>
    <Sheet open={!!selected} onOpenChange={(open) => !open && setSelected(null)}>{selected && <NodeGuide node={selected} />}</Sheet>
  </Page>
}

function RoadmapStop({ node, onClick }: { node: RoadmapNode; onClick: () => void }) { return <StopButton $x={node.x} $y={node.y} $optional={node.optional} onClick={onClick}><span className="stop-marker">{node.optional ? '+' : node.stage.split('·')[0].trim()}</span><span className="stop-card"><small>{node.kicker}</small><strong>{node.title}</strong><i>Open guide <ArrowUpRight size={13} /></i></span></StopButton> }
function NodeGuide({ node }: { node: RoadmapNode }) { return <SheetContent><GuideHeader><Badge variant={node.optional ? 'gold' : 'default'}>{node.optional ? 'Optional specialism' : node.stage}</Badge><p>{node.kicker}</p><SheetTitle>{node.title}</SheetTitle><div className="guide-rule" /></GuideHeader><GuideBody><section><h3>The overview</h3><p>{node.description}</p></section><section><h3>Why it matters</h3><p>{node.why}</p></section><section><h3>Your next moves</h3><ul>{node.actions.map((action) => <li key={action}><CheckCircle2 size={17} />{action}</li>)}</ul></section><section><h3>Keep learning</h3>{node.resources.map((resource) => <a className="resource" href={resource.href} target="_blank" rel="noreferrer" key={resource.label}>{resource.label}<ArrowUpRight size={17} /></a>)}</section></GuideBody></SheetContent> }

const Page = styled.div`min-height:100vh;background:#fffefa;color:#26342c;`
const Header = styled.header`height:76px;max-width:1240px;margin:auto;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 28px;border-bottom:1px solid #e8e3d7;.back{display:flex;align-items:center;gap:7px;color:#466555;text-decoration:none;font-size:13px;font-weight:600}.brand{display:flex;align-items:center;gap:10px;color:#163b2b;text-decoration:none;font:700 18px Georgia,serif}.brand span{display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:#163b2b;color:#f5e9c9;font:700 10px ui-sans-serif,system-ui;letter-spacing:.04em}.route-label{justify-self:end;color:#798177;text-transform:uppercase;letter-spacing:.11em;font-size:10px;font-weight:700}.route-label b{display:inline-grid;place-items:center;width:22px;height:22px;margin-left:8px;border:1px solid #c9b77f;border-radius:50%;color:#8d713a;font-size:10px}@media(max-width:650px){height:68px;grid-template-columns:1fr auto;padding:0 20px;.brand{display:flex;justify-self:end;font-size:15px;gap:7px}.brand span{width:28px;height:28px;font-size:9px}.route-label{display:none}}`
const RoadmapSection = styled.section`max-width:1240px;min-height:calc(100vh - 76px);margin:auto;padding:83px 78px 55px;background:#173c2b;color:#f7f4e9;@media(max-width:760px){padding:56px 20px 30px}`
const Eyebrow = styled.div`display:flex;align-items:center;gap:9px;color:#c9aa66;text-transform:uppercase;letter-spacing:.13em;font-size:10px;font-weight:700;span{height:1px;width:25px;background:#c9aa66;}`
const RoadmapHeader = styled.div`display:flex;justify-content:space-between;gap:50px;h1{margin:14px 0 0;font:44px/1.04 Georgia,serif;letter-spacing:-.045em;em{color:#dcc585;font-style:italic}}p{margin:28px 0 0;max-width:346px;color:#c0d0c4;font-size:14px;line-height:1.7}@media(max-width:720px){display:block;h1{font-size:36px}}`
const Legend = styled.div`display:flex;gap:24px;margin:36px 0 0;padding-top:16px;border-top:1px solid rgba(235,241,230,.18);color:#c9d5ca;font-size:11px;span{display:flex;align-items:center;gap:6px}i{display:inline-block;width:8px;height:8px;border-radius:50%}.core-dot{background:#e1c67d}.optional-dot{border:1px solid #e1c67d}@media(max-width:720px){display:grid;grid-template-columns:max-content max-content;gap:11px 18px;span:last-child{grid-column:1/-1}}`
const RoadmapCanvas = styled.div<{ $height: number }>`position:relative;height:${p => p.$height}px;margin:64px -40px 0;.connectors{position:absolute;inset:0;width:100%;height:100%;overflow:visible;line{stroke:#8dad99;stroke-width:.23;stroke-dasharray:.7 .7;}}@media screen and (max-width:760px){&&{height:auto!important;margin:22px 0 0;display:flex!important;flex-direction:column;gap:11px}.connectors{display:none!important}}`
const StopButton = styled.button<{ $x:number;$y:number;$optional?:boolean }>`position:absolute;left:${p=>p.$x}%;top:${p=>p.$y}%;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;width:190px;border:0;background:transparent;color:inherit;cursor:pointer;z-index:1;.stop-marker{display:grid;place-items:center;width:35px;height:35px;border:1px solid ${p=>p.$optional?'#dfc984':'#f0e6bf'};border-radius:50%;background:#173c2b;color:#f2dfaa;font:13px Georgia,serif;z-index:1}.stop-card{width:174px;margin-top:8px;padding:12px 13px 10px;border:1px solid ${p=>p.$optional?'rgba(224,199,131,.4)':'rgba(215,232,217,.28)'};background:${p=>p.$optional?'#234733':'#1c4633'};box-shadow:0 7px 15px rgba(6,29,18,.16);text-align:left;transition:.2s;small{display:block;color:${p=>p.$optional?'#e0c783':'#bdd2c1'};font-size:9px;text-transform:uppercase;letter-spacing:.1em}strong{display:block;margin-top:5px;color:#faf7ed;font:17px/1.07 Georgia,serif}i{display:flex;align-items:center;gap:4px;margin-top:11px;color:#b9cebd;font-size:10px;font-style:normal;opacity:0;transition:.15s}}&:hover .stop-card,&:focus-visible .stop-card{transform:translateY(-3px);border-color:#e0ca8b}&:hover i,&:focus-visible i{opacity:1}@media screen and (max-width:760px){&&{position:relative!important;left:auto!important;top:auto!important;transform:none!important;width:100%;flex-direction:row;gap:11px;text-align:left}.stop-marker{flex:0 0 35px}.stop-card{margin:0;width:100%;display:flex;align-items:center;flex-wrap:wrap;gap:4px 9px;padding:13px 15px;small{width:100%;}strong{margin:0;font-size:18px}i{margin:0 0 0 auto;opacity:1}}}`
const RoadmapFoot = styled.div`display:flex;gap:11px;max-width:650px;margin:25px auto 0;padding:19px 23px;border:1px solid rgba(226,201,133,.28);background:rgba(10,35,24,.24);color:#d0dbc9;font-size:12px;line-height:1.6;svg{flex:none;color:#e0c783}`
const GuideHeader = styled.div`padding:58px 42px 0;background:#eff2e9;p{margin:19px 0 6px;color:#906b2b;font-size:12px;text-transform:uppercase;letter-spacing:.1em}.guide-rule{width:49px;height:3px;margin-top:24px;background:#c8a455}`
const GuideBody = styled.div`padding:30px 42px 55px;section{margin:0 0 30px}h3{margin:0 0 9px;color:#183827;font:21px Georgia,serif}p{margin:0;color:#626b63;font-size:15px;line-height:1.7}ul{padding:0;margin:0;list-style:none;li{display:flex;gap:10px;margin:0 0 12px;color:#465149;font-size:14px;line-height:1.45}svg{flex:none;margin-top:1px;color:#568165}}.resource{display:flex;align-items:center;justify-content:space-between;margin-top:9px;padding:13px 14px;border:1px solid #ddd8c9;color:#23523b;font-size:13px;font-weight:600;text-decoration:none;&:hover{background:#f2f5ef}}`
