import { useState } from 'react'
import { ArrowRight, ArrowUpRight, BookOpen, BriefcaseBusiness, CheckCircle2, Route } from 'lucide-react'
import styled from 'styled-components'
import { Badge } from './components/ui/badge'
import { Button } from './components/ui/button'
import { Sheet, SheetContent, SheetTitle } from './components/ui/sheet'

const brokerUrl = `${import.meta.env.BASE_URL}broker/`
const bdmUrl = `${import.meta.env.BASE_URL}bdm/`

function App() {
  const [showGuide, setShowGuide] = useState(false)
  return <Page>
    <Header><Brand href="#top" aria-label="Mortgage Paths home"><span>MP</span>Mortgage Paths</Brand><Nav><a href="#careers">Careers</a><a href="#how-it-works">How it works</a><a href="#about">About</a></Nav><Button variant="outline" size="sm" onClick={() => setShowGuide(true)}><BookOpen size={15} /> Start here</Button></Header>
    <main id="top">
      <Hero><HeroCopy><Eyebrow><span /> Career roadmaps for the mortgage industry</Eyebrow><h1>A career in mortgages.<br /><em>Mapped out.</em></h1><p>Clear, practical pathways for getting started in the UK mortgage industry — beginning with mortgage broking.</p><HeroActions><a className="primary-link" href={brokerUrl}>Explore the broker pathway <ArrowRight size={17} /></a><button className="text-link" onClick={() => setShowGuide(true)}>Not sure where to begin? <ArrowUpRight size={16} /></button></HeroActions></HeroCopy><HeroMark aria-hidden="true"><div className="arch arch-one" /><div className="arch arch-two" /><div className="sun" /><p>MAKE<br />IT<br />POSSIBLE</p></HeroMark></Hero>
      <SectionIntro id="careers"><div><Eyebrow><span /> Choose a direction</Eyebrow><h2>Start with a role.<br />Build towards a career.</h2></div><p>Each pathway breaks a big career question into small, useful steps. Follow them in order, take your time, and explore the branches that feel right for you.</p></SectionIntro>
      <CareerList><CareerCard href={brokerUrl}><div className="number">01</div><div className="card-icon"><Route size={27} /></div><div className="career-copy"><Badge>Available now</Badge><h3>Mortgage Broker</h3><p>Help people make confident decisions about buying, moving and refinancing their home.</p><span>8 core steps · 3 optional paths</span></div><div className="explore">Explore pathway <ArrowUpRight size={19} /></div></CareerCard><CareerCard href={bdmUrl}><div className="number">02</div><div className="card-icon"><BriefcaseBusiness size={25} /></div><div className="career-copy"><Badge>Available now</Badge><h3>Mortgage BDM</h3><p>Build relationships with brokers and help a lender grow its mortgage business.</p><span>12 core steps · 5 optional paths</span></div><div className="explore">Explore pathway <ArrowUpRight size={19} /></div></CareerCard></CareerList>
      <HowItWorks id="how-it-works"><Eyebrow><span /> How to use a pathway</Eyebrow><div className="steps"><div><b>01</b><h3>Explore the map</h3><p>See the full journey at a glance, from first curiosity to specialist routes.</p></div><div><b>02</b><h3>Open a stop</h3><p>Find clear context, practical actions and a few useful places to learn more.</p></div><div><b>03</b><h3>Make it yours</h3><p>Choose the next small action that works for you. There’s no single perfect route in.</p></div></div></HowItWorks>
    </main>
    <Footer id="about"><Brand href="#top"><span>MP</span>Mortgage Paths</Brand><p>Helping the next generation find their place in the mortgage industry.</p><small>Built as an educational POC. Always check qualification and regulatory information with the relevant provider.</small></Footer>
    <Sheet open={showGuide} onOpenChange={setShowGuide}><SheetContent><GuideStart /></SheetContent></Sheet>
  </Page>
}

function GuideStart() { return <><GuideHeader><Badge variant="gold">Welcome</Badge><p>New to the industry?</p><SheetTitle>Start where you are.</SheetTitle><div className="guide-rule" /></GuideHeader><GuideBody><section><h3>You don’t need a perfect plan</h3><p>Mortgage broking is a people-focused career with lots of ways in. You can begin by exploring the role, then add knowledge and qualifications as you go.</p></section><section><h3>A useful first week</h3><ul><li><CheckCircle2 size={17} />Read the first two roadmap stops.</li><li><CheckCircle2 size={17} />Look at a handful of local job descriptions.</li><li><CheckCircle2 size={17} />Write down the parts of the role that interest you.</li></ul></section><a className="guide-link" href={brokerUrl}>Open the broker pathway <ArrowRight size={17} /></a></GuideBody></> }
export default App

const Page = styled.div`display:flex;min-height:100vh;flex-direction:column;overflow:hidden;background:#fffefa;color:#26342c;main{flex:1;}`
const Header = styled.header`height:76px;max-width:1240px;margin:auto;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;padding:0 28px;border-bottom:1px solid #e8e3d7;@media(max-width:620px){padding:0 18px;}`
export const Brand = styled.a`display:flex;align-items:center;gap:10px;color:#163b2b;text-decoration:none;font-family:Georgia,serif;font-weight:700;font-size:18px;span{display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:#163b2b;color:#f5e9c9;font:700 10px ui-sans-serif,system-ui;letter-spacing:.04em;}`
const Nav = styled.nav`display:flex;justify-content:flex-end;gap:31px;margin-right:24px;a{color:#5d655f;text-decoration:none;font-size:14px;white-space:nowrap;&:hover{color:#163b2b}}@media(max-width:900px){display:none;}`
const Hero = styled.section`max-width:1240px;margin:auto;min-height:522px;padding:88px 78px 75px;display:flex;align-items:center;justify-content:space-between;position:relative;background:linear-gradient(108deg,#f1f3e9 0%,#f7f6ef 60%,#e7eee8 100%);@media(max-width:760px){padding:64px 28px 52px;min-height:auto}`
const HeroCopy = styled.div`position:relative;z-index:1;max-width:650px;h1{margin:15px 0 18px;color:#153b2a;font:clamp(43px,5.3vw,74px)/.99 Georgia,serif;letter-spacing:-.055em;em{color:#a46e2b;font-style:italic}}p{max-width:470px;margin:0;color:#5d655f;font-size:17px;line-height:1.65}`
export const Eyebrow = styled.div`display:flex;align-items:center;gap:9px;color:#7a6a45;text-transform:uppercase;letter-spacing:.13em;font-size:10px;font-weight:700;span{height:1px;width:25px;background:#a67c39;}`
const HeroActions = styled.div`display:flex;align-items:center;gap:25px;margin-top:32px;.primary-link,.guide-link{display:inline-flex;align-items:center;justify-content:center;gap:8px;height:48px;padding:0 20px;border-radius:6px;background:#163b2b;color:#fff;text-decoration:none;font-size:16px;font-weight:700}.text-link{display:flex;align-items:center;gap:5px;border:0;background:transparent;color:#325743;font-size:13px;text-decoration:underline;text-underline-offset:4px;cursor:pointer}@media(max-width:510px){flex-direction:column;align-items:flex-start;gap:17px;}`
const HeroMark = styled.div`width:282px;height:330px;position:relative;color:#173d2d;font-family:Georgia,serif;font-size:21px;line-height:.85;letter-spacing:-.06em;.arch{position:absolute;border:1px solid #9eb5a7;border-radius:50% 50% 0 0;border-bottom:0}.arch-one{width:237px;height:292px;right:-20px;bottom:-57px}.arch-two{width:166px;height:222px;right:15px;bottom:-57px}.sun{position:absolute;width:65px;height:65px;border-radius:50%;background:#d49d45;top:39px;right:96px}p{position:absolute;bottom:0;right:23px;color:#214837;font-size:26px;line-height:.83}@media(max-width:900px){opacity:.35;position:absolute;right:-40px;bottom:-100px}@media(max-width:560px){display:none;}`
const SectionIntro = styled.section`max-width:1084px;margin:0 auto;padding:105px 0 45px;display:flex;justify-content:space-between;gap:70px;h2{margin:13px 0 0;color:#183627;font:43px/1.03 Georgia,serif;letter-spacing:-.045em}p{max-width:365px;margin:27px 0 0;color:#687168;font-size:15px;line-height:1.7}@media(max-width:760px){padding:70px 28px 35px;display:block;h2{font-size:36px}}`
const CareerList = styled.div`display:grid;gap:14px;`
const CareerCard = styled.a`max-width:1084px;width:calc(100% - 56px);margin:0 auto;border:1px solid #d8d4c6;background:#fffefa;display:grid;grid-template-columns:42px 68px 1fr auto;gap:17px;align-items:center;padding:28px 32px;text-align:left;text-decoration:none;cursor:pointer;transition:.2s;&:hover{border-color:#a6b6a8;transform:translateY(-2px);box-shadow:0 12px 27px rgba(30,55,41,.07)}.number{font:17px Georgia,serif;color:#b28b4d}.card-icon{display:grid;place-items:center;width:50px;height:50px;border-radius:50%;background:#e7efe9;color:#20513b}.career-copy{h3{margin:8px 0 7px;color:#173b2a;font:27px Georgia,serif}p{margin:0 0 9px;color:#626b64;font-size:14px;line-height:1.5}span{color:#8a8474;font-size:12px}}.explore{display:flex;align-items:center;gap:8px;color:#1b4a34;font-size:13px;font-weight:700}@media(max-width:650px){width:calc(100% - 36px);grid-template-columns:42px 58px 1fr;padding:23px 18px;.explore{display:none}.career-copy h3{font-size:22px}}`
const HowItWorks = styled.section`max-width:1084px;margin:0 auto;padding:113px 0 107px;.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:55px;margin-top:39px}.steps div{border-top:1px solid #d9d5c8;padding-top:18px}.steps b{color:#a07534;font:16px Georgia,serif}.steps h3{margin:22px 0 8px;color:#244231;font:24px Georgia,serif}.steps p{margin:0;color:#697069;font-size:14px;line-height:1.65}@media(max-width:760px){padding:70px 28px;.steps{grid-template-columns:1fr;gap:28px}}`
const Footer = styled.footer`display:grid;grid-template-columns:1fr 1.5fr;gap:10px;max-width:1240px;width:100%;margin:auto auto 0;padding:38px 78px;background:#eeeadd;color:#5e675f;p{margin:0;font-size:13px;align-self:center}small{grid-column:1/-1;margin-top:17px;color:#828277;font-size:10px}@media(max-width:700px){display:block;padding:32px 28px;p{margin:18px 0}small{display:block;margin-top:25px}}`
const GuideHeader = styled.div`padding:58px 42px 0;background:#eff2e9;p{margin:19px 0 6px;color:#906b2b;font-size:12px;text-transform:uppercase;letter-spacing:.1em}.guide-rule{width:49px;height:3px;margin-top:24px;background:#c8a455}`
const GuideBody = styled.div`padding:30px 42px 55px;section{margin:0 0 30px}h3{margin:0 0 9px;color:#183827;font:21px Georgia,serif}p{margin:0;color:#626b63;font-size:15px;line-height:1.7}ul{padding:0;margin:0;list-style:none;li{display:flex;gap:10px;margin:0 0 12px;color:#465149;font-size:14px;line-height:1.45}svg{flex:none;margin-top:1px;color:#568165}}.guide-link{display:inline-flex;align-items:center;gap:8px;padding:13px 15px;background:#163b2b;color:#fff;text-decoration:none;font-size:14px;font-weight:700;border-radius:5px}`
